name: Yann Schaub - Portfolio
favicon: null
layout_spectrum: 0.8453319275286049
typography_spectrum: 0.2649828519206494
title: My UX Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6213343278504908
  lightness: 0.519952779635787
  saturation: 0.747506650397554
  rhythmicContrast: 0.5240322649478912
purpose: []
